# Generated by Django 3.2.8 on 2021-10-27 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Host',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hostname', models.CharField(max_length=100)),
                ('port', models.CharField(max_length=10)),
            ],
            options={
                'ordering': ['hostname'],
            },
        ),
        migrations.DeleteModel(
            name='Destination',
        ),
    ]
