# Generated by Django 3.2.8 on 2021-10-29 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restapp', '0003_auto_20211028_1315'),
    ]

    operations = [
        migrations.AddField(
            model_name='remote',
            name='disable_hashcheck',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='remote',
            name='password',
            field=models.CharField(default='pass', max_length=100),
        ),
        migrations.AddField(
            model_name='remote',
            name='type',
            field=models.CharField(default='sftp', max_length=50),
        ),
        migrations.AddField(
            model_name='remote',
            name='user',
            field=models.CharField(default='user', max_length=30),
        ),
        migrations.AlterField(
            model_name='remote',
            name='port',
            field=models.IntegerField(),
        ),
    ]
