# Generated by Django 3.2.8 on 2021-11-02 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restapp', '0004_auto_20211029_1222'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='remote',
            options={'ordering': ['_type']},
        ),
        migrations.RemoveField(
            model_name='remote',
            name='type',
        ),
        migrations.AddField(
            model_name='remote',
            name='_type',
            field=models.CharField(choices=[('sftp', 'sftp'), ('ftp', 'ftp'), ('local', 'local')], default='sftp', max_length=50),
        ),
    ]
