# Generated by Django 3.2.9 on 2021-11-18 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restapp', '0005_auto_20211102_0704'),
    ]

    operations = [
        migrations.CreateModel(
            name='CopyNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_name', models.CharField(max_length=100)),
                ('copy_date_time', models.DateTimeField(auto_now_add=True, verbose_name='Дата копирования')),
                ('copied_from', models.CharField(max_length=250)),
                ('copied_to', models.CharField(max_length=250)),
            ],
            options={
                'ordering': ['copy_date_time'],
            },
        ),
    ]
