# Generated by Django 3.2.9 on 2021-11-18 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restapp', '0006_copynote'),
    ]

    operations = [
        migrations.AlterField(
            model_name='copynote',
            name='copy_date_time',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата и время копирования'),
        ),
    ]
