# Generated by Django 3.2.9 on 2021-11-23 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restapp', '0007_alter_copynote_copy_date_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='copynote',
            name='copy_date_time',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Copy datetime'),
        ),
    ]
